[project]
name = "dj-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "yt-dlp",
    "ytmusicapi",
    "pandas",
    "numpy",
    "scikit-learn",
    "category-encoders",
    "musicbrainzngs",
    "sounddevice",
]
